"""Add reply column to reviews

Revision ID: 7338e99a74c8
Revises: 27bb1b389ad5
Create Date: 2026-06-12 11:27:42.242528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7338e99a74c8'
down_revision: Union[str, Sequence[str], None] = '27bb1b389ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reply', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reply')
    # ### end Alembic commands ###
